version: '3.9'

services:
    case-elsa-server:
        image: phuongnguyendeveloper/case-elsa-server:1.0.0
        ports:
            - 8080:80
        depends_on:
            - mssql-server

    mssql-server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            SA_PASSWORD: Abc!2345
            ACCEPT_EULA: Y